# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='marcaa',
            new_name='marca',
        ),
    ]
