# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_auto_20160813_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
