# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0003_auto_20160813_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
