# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0004_device_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsos',
            name='BPM2',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pulsos',
            name='BPM3',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pulsos',
            name='BPM4',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pulsos',
            name='BPM5',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='pulsos',
            name='BPM',
            field=models.CharField(max_length=8),
        ),
    ]
