# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0005_auto_20160819_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulsos',
            name='BPM2',
        ),
        migrations.RemoveField(
            model_name='pulsos',
            name='BPM3',
        ),
        migrations.RemoveField(
            model_name='pulsos',
            name='BPM4',
        ),
        migrations.RemoveField(
            model_name='pulsos',
            name='BPM5',
        ),
    ]
