# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0006_auto_20160825_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.IntegerField(blank=True)),
                ('t2', models.IntegerField(blank=True)),
                ('p1', models.IntegerField(blank=True)),
                ('p2', models.IntegerField(blank=True)),
                ('IBI', models.IntegerField(blank=True)),
            ],
        ),
    ]
