# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0007_grafica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
