# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0008_auto_20160826_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsos',
            name='hora',
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
    ]
