# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0009_pulsos_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsos',
            name='hora',
            field=models.TimeField(blank=True, default=b'09:37:39'),
        ),
    ]
