# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0010_auto_20160826_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsos',
            name='hora',
            field=models.TimeField(blank=True, default=b'00:25:45'),
        ),
    ]
