# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0011_auto_20160901_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafica',
            name='IBI',
        ),
        migrations.RemoveField(
            model_name='grafica',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='grafica',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='grafica',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='grafica',
            name='t2',
        ),
        migrations.AddField(
            model_name='grafica',
            name='estable',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='grafica',
            name='periodo',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='grafica',
            name='picos',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='grafica',
            name='pulso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaps.Pulsos'),
        ),
        migrations.AddField(
            model_name='grafica',
            name='valles',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='pulsos',
            name='hora',
            field=models.TimeField(blank=True, default=b'18:54:23'),
        ),
    ]
