# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0012_auto_20160901_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsos',
            name='hora',
            field=models.TimeField(blank=True, default=b'23:31:32'),
        ),
    ]
