# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaMedica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichamedica',
            old_name='diagnostico',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='fichamedica',
            old_name='sintomas',
            new_name='detalles',
        ),
    ]
