# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tipon',
            field=models.CharField(blank=True, choices=[('M', 'Mensaje'), ('A', 'Alertas'), ('N', 'Notificacion')], max_length=1, null=True),
        ),
    ]
