# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_auto_20160819_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='titulo',
            field=models.TextField(),
        ),
    ]
