# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 23:02
from __future__ import unicode_literals

import Corazon.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
        ('Corazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='devide1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaps.Device'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=10, validators=[Corazon.validators.validacion_10digit, Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=10, validators=[Corazon.validators.validacion_10digit, Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=3, validators=[Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[Corazon.validators.validacion_esDigito]),
        ),
    ]
